version: '3.1'
services:
  sentry_webhook:
    image: xuanwolei/sentry_webhook:v1
    restart: always
    environment:
      - TOKEN=xxx
      - TEMPLATE=- 项目：@{project_name}\n- level：@{level}\n## error：\n```\n@{title}\n@{culprit}\n@{location}\n```\n- [查看更多](@{url})\n
      - ADDR = 0.0.0.0:80
    network_mode: "sentry-self-hosted_default"
#    ports:
#      - 8910:80